### ISSUE TITLE
Create buttons for categories like "Issue Assignment Requests", "PR Verification Requests", "Active Issues" etc.

### ISSUE THREAD

**Issue by ankitsangwan1999** [ContriHUB/ContriHUB-23#150]
Create buttons for categories like "Issue Assignment Requests", "PR Verification Requests", "Active Issues" etc. on the profiles of Students and Mentors. For e.g. On Mentor's Profile Page "Issue Assignment Requests" cards should only be shown after clicking on the "Issue Assignment Requests" category button. 

These buttons should be placed just after the Profile-Card.

**Comment by khwab-41** [comment]
Hello @ankitsangwan1999 I would like to work on this issue. Can you please assign it to me?
ps: this is my first time contributing to open source, and I find this one good enough to start. Thank You!
