### ISSUE TITLE
Different card color based on levels

### ISSUE THREAD

**Issue by shank03** [ContriHUB/ContriHUB-23#161]
Life could be a dream 🎶 
Sh-boom, if anyone could change colors for levels 🎶 

![image](https://github.com/ContriHUB/ContriHUB-23/assets/39261691/6b3bdf97-ffd7-4b02-beed-ba97d60de92b)

**Comment by CoderRedwing** [comment]
can i work on it

**Comment by eleensmathew** [comment]
Hi @PriyavKaneria and @shank03 can i work on this?

**Comment by priyanshagra** [comment]
can i work on this

**Comment by priyanshagra** [comment]
please assign this to me

**Comment by PriyavKaneria** [comment]
According to rules @nandika-a has been assigned the issue on contrihub
