### ISSUE TITLE
add hower effect on project section 

### ISSUE THREAD

**Issue by CoderRedwing** [ContriHUB/ContriHUB-23#163]
Please choose your issue template from the following options:

# 1. 🐛Bug-Report
If something isn't working as expected 🤔

### Steps to reproduce

1.
2.
3.
4.

### Detailed Description (screenshots, code snippets etc.)

# 2. 🚀Feature Request
I have a suggestion (and may want to implement it 🙂)!

### Description
*Please describe the problem you are trying to solve.*

### Why is this feature important to you?
*Is your feature request related to a problem? Please describe.*

### Describe the solution you'd like
*Please describe the desired behavoiur.*

### Additional context
*Please describe alternative solutions or features you have considered*
![image](https://github.com/ContriHUB/ContriHUB-23/assets/115499559/a5b14ccd-9017-4783-b995-1d1903f1ba06)

**Comment by CoderRedwing** [comment]
if you want chane this kindly assign me

**Comment by shank03** [comment]
You clearly did not follow the issue template.

**Comment by CoderRedwing** [comment]
i just want to tell you if want this change i can do it

**Comment by shank03** [comment]
No thank you, that feature is not needed.
