### ISSUE TITLE
Fix dark mode  for new Appended cards

### ISSUE THREAD

**Issue by techimanshu8** [ContriHUB/ContriHUB-23#78]

**Comment by ankitsangwan1999** [comment]
Hi @techimanshu8, Don't open issues by yourself without asking permission from a mentor. First, you need to contact us via dm/mail on contriHUB email and report the issue. After that, we will decide whether to make it part of contrihub-21 or not. All These issues are handled carefully so, creating new issues without care may cause problems for others.  

That being said I hereby close this issue.
